import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "./components";
const inter = Inter({ subsets: ["latin"] });
import { GoogleOAuthProvider } from "@react-oauth/google";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="cupcake">
      <GoogleOAuthProvider clientId={process.env.GOOGLE_CLIENT_ID!}>
        <body className={inter.className}>
          <Navbar />
          <div style={{ height: "calc(100vh - 80px)", overflow: "auto" }}>
            {children}
          </div>
        </body>
      </GoogleOAuthProvider>
    </html>
  );
}
